# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(username: "micah_white", email: "micah@example.com", password_digest: "micah_password", first_name: "Micah", last_name: "White", bio: "Lives in Beacon NY")
User.create(username: "jessica_white", email: "jessica@example.com", password_digest: "jessica_password", first_name: "Jessica", last_name: "White", bio: "Likes to bake and write stories")
User.create(username: "henry_white", email: "henry@example.com", password_digest: "henry_password", first_name: "Henry", last_name: "White", bio: "Mostly writes comic books")
User.create(username: "rowen_white", email: "rowen@example.com", password_digest: "rowen_password", first_name: "Rowen", last_name: "White", bio: "Enjoys scribbling and reading Mo Willems books")
Genre.create(name: "Fiction")
Genre.create(name: "Experimental fiction")
Genre.create(name: "Flash fiction")
Genre.create(name: "Short story")
Genre.create(name: "Science fiction")
Genre.create(name: "Mystery")
Genre.create(name: "Nonfiction")
Genre.create(name: "Creative nonfiction")
Genre.create(name: "Memoir")
Genre.create(name: "Biography")
Genre.create(name: "Autobiography")
Genre.create(name: "Poetry")
Work.create(title: "The Great Ratsby", description: "A rat loses everything.", content: "Once upon a time there was a rat that wanted approval from everyone and he lived in a huge house and had lavish parties and many people adored him and wanted to be like him but he died and it was all for nothing.", user_id: 1, genre_id: 1)
Work.create(title: "On Our Time", description: "A short story that is sad", content: "The morning was cool, the ground wet. We grabbed our poles. We heard the fishing was good in the morning. We grabbed wine as well.", user_id: 2, genre_id: 4)
Work.create(title: "The Road Most Traveled", description: "A guy has no choices and stays on the same road he is always on.", content: "This damn road never changes. I wish there were a fork in the road or something. Guess I'll just keep going.", user_id: 3, genre_id: 12)
Work.create(title: "Evolution and You", description: "An article exploring evolution's impact on your daily behavior", content: "Your reptilian brain controls everything you do and influences how you think and speak and project your identity.", user_id: 4, genre_id: 7)
Comment.create(content: "This book sucks", user_id: 4, work_id: 1)
Comment.create(content: "Excellent. Thought provoking. Gorgeous and lyrical.", user_id: 2, work_id: 3)
Comment.create(content: "Wow, I never throught about any of this. Fantastic!", user_id: 1, work_id: 4)
Comment.create(content: "I love anything about fishing and drinking", user_id: 3, work_id: 2)